base_url = "https://blog.luning.wang"
title = "圣堂武士文献馆"
date = 2019-01-01
description = "卖萌"

theme = "anatole-zola"

default_language = "en"

compile_sass = true
build_search_index = true

[markdown]
highlight_code = true

[extra]
# Put all your custom variables here
author = "Lucas"

taxonomies = [
  {name = "tags"},
]

[languages.en.translations]
about = "About"
home = "Home"
tags = "Tags"
archive = "Archive"
links = "Links"
next_page = "Next Page"
last_page = "Last Page"

[languages.zh.translations]
home = "首页"
about = "关于"
tags = "标签"
archive = "归档"
links = "友链"
next_page = "下一页"
last_page = "上一页"

[extra.social]
github = "deadwind4"

[extra.show]
tags = true
